#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
GLPI_VERSION = data.get("GLPI_VERSION", "10.0.16")
glpi_config = {
    "VERSION_GLPI": GLPI_VERSION,
}
agent.write_envfile("glpi.env", glpi_config)
#agent.dump_env()
