#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import secrets

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

def generate_random_password():
    return secrets.token_urlsafe(16)
#This is specific to you module, so you need to change it accordingly.

MARIA_DB_ROOT_PASSWORD = generate_random_password()
MARIA_DB_DATABASE = "glpi"
MARIA_DB_USER = "glpi"
MARIA_DB_PASSWORD = generate_random_password()
MARIA_DB_AUTO_UPGRADE = 1

mariadb_config = {
    "MARIADB_ROOT_PASSWORD": MARIA_DB_ROOT_PASSWORD,
    "MARIADB_DATABASE": MARIA_DB_DATABASE,
    "MARIADB_USER": MARIA_DB_USER,
    "MARIADB_PASSWORD": MARIA_DB_PASSWORD,
    "MARIADB_AUTO_UPGRADE": MARIA_DB_AUTO_UPGRADE
}
agent.write_envfile("database.env", mariadb_config)

# GLPI DB

glpi_db = {
    "TIMEZONE": "Europe/Brussels",
    "MARIADB_DB_TYPE": "mysql",
    "MARIADB_DB_HOST": "mariadb-app",
    "MARIADB_DB_PORT": "3306",
    "MARIADB_DB_USER": MARIA_DB_USER,
    "MARIADB_DB_PASSWORD": MARIA_DB_PASSWORD,
    "MARIADB_DB_NAME": MARIA_DB_DATABASE
}
agent.write_envfile("glpi-db.env", glpi_db)

#agent.dump_env()
